// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace E_commerce.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ContraintsProductAndCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContraintsProductAndCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202003051254432_ContraintsProductAndCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
