// <auto-generated />
namespace E_commerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProductVariants : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductVariants));
        
        string IMigrationMetadata.Id
        {
            get { return "202006201423227_ProductVariants"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
